package tup.simple.controllers;

import java.sql.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import tup.simple.models.cargos;
import tup.simple.models.empleados;
import tup.simple.repositories.empleadosRepository;

@Controller // This means that this class is a Controller
// La URL que vaya en la anotación habrá que agregarla detrás del puerto :8080
// en todas las llamadas a esta aplicación.
// Por ejemplo @RequestMapping("/user") resultaría en lo siguiente:
// localhost:8080/anime.... y detrás de esto habría que agregar el
// resto de la URL.
// En este caso, no necesitamos nada, y queda simplemente localhost:8080
@RequestMapping("/empleados")
public class empleadosController {
    // This means to get the bean called userRepository
    // which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private empleadosRepository _empleadosRepository;

    @PostMapping("/add") // Map ONLY POST Requests
    public @ResponseBody String addNewEmployee(@RequestParam String nombre, @RequestParam Character sexo,
    @RequestParam Date fechanac, @RequestParam Date fechaincor,@RequestParam Float salario, @RequestParam Float comision,@RequestParam cargos idcargo, @RequestParam Long jefe,@RequestParam Long codigodepto) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        empleados n = new empleados();
        n.setNombre(nombre);
        n.setSexo(sexo);
        n.setFechanac(fechanac);
        n.setFechaincor(fechaincor);
        n.setSalario(salario);
        n.setComision(comision);
        n.setCargo(idcargo);
        n.setJefe(jefe);
        n.setCodigodepto(codigodepto);
        _empleadosRepository.save(n);
        return "Saved";
    }

    @PostMapping("/delete/{id}") // Map ONLY POST Requests
    public @ResponseBody String deleteEmployeeById(@PathVariable Long id) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        _empleadosRepository.deleteById(id);
        return "Deleted";
    }

    @GetMapping("/all")
    public @ResponseBody String getAllEmployees() {
        // This returns a JSON or XML with the users
        Iterable<empleados> iterable = _empleadosRepository.findAll();
        String resp = "<style>\n"
                +"#users {\n"
                +"  font-family: Arial, Helvetica, sans-serif;\n"
                +"  border-collapse: collapse;\n"
                +"  width: 100%;}\n"

                +"#users td, #users th {\n"
                +"  border: 1px solid #ddd;\n"
                +"  padding: 8px;}\n"

                +"#users tr:nth-child(even){background-color: #f2f2f2;}\n"

                +"#users tr:hover {background-color: #ddd;}\n"

                +"#users th {\n"
                +"  padding-top: 12px;\n"
                +"  padding-bottom: 12px;\n"
                +"  text-align: left;\n"
                +"  background-color: #04AA6D;\n"
                +"  color: white;}\n"
                +"</style>";
        resp += "<table id ='users'>"
                + "<tr>"
                + "<th>Id</th>"
                + "<th>Nombre</th>"
                + "<th>Sexo</th>"
                + "<th>Fecha Nacimiento</th>"
                + "<th>Fecha Incorporacion</th>"
                + "<th>Salario</th>"
                + "<th>Comision</th>"
                + "<th>Cargo</th>"
                + "<th>Jefe</th>"
                + "<th>Codigo depto</th>"
                + "</tr>";
        // No puedo usar forEach() con una función lambda
        // porque el scope de las variables no lo permite.
        for (empleados employ : iterable) {
            resp += "<tr>"
                    + "<td>" + employ.getId() + "</td>"
                    + "<td>" + employ.getNombre() + "</td>"
                    + "<td>" + employ.getSexo() + "</td>"
                    + "<td>" + employ.getFechanac() + "</td>"
                    + "<td>" + employ.getFechaincor() + "</td>"
                    + "<td>" + employ.getSalario() + "</td>"
                    + "<td>" + employ.getComision() + "</td>"
                    + "<td>" + employ.getCargo() + "</td>"
                    + "<td>" + employ.getJefe() + "</td>"
                    + "<td>" + employ.getCodigodepto() + "</td>"
                    + "</tr>";
        }
        return resp + "</table>";
    }

    @GetMapping("")
    public @ResponseBody String hola() {
        return "Hola";
    }
}
